{
   "_data":[
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-01-01",
            "_formattedValue":"1/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":10634,
            "_formattedValue":"10,634.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-02-01",
            "_formattedValue":"2/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":5227,
            "_formattedValue":"5,227.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-03-01",
            "_formattedValue":"3/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":1753,
            "_formattedValue":"1,753.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-04-01",
            "_formattedValue":"4/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":9708,
            "_formattedValue":"9,708.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-05-01",
            "_formattedValue":"5/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":3872,
            "_formattedValue":"3,872.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-06-01",
            "_formattedValue":"6/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":3827,
            "_formattedValue":"3,827.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-07-01",
            "_formattedValue":"7/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":6102,
            "_formattedValue":"6,102.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-08-01",
            "_formattedValue":"8/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":4728,
            "_formattedValue":"4,728.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-09-01",
            "_formattedValue":"9/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":7347,
            "_formattedValue":"7,347.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-10-01",
            "_formattedValue":"10/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":9522,
            "_formattedValue":"9,522.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-11-01",
            "_formattedValue":"11/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":7029,
            "_formattedValue":"7,029.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2018-12-01",
            "_formattedValue":"12/1/2018"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":7056,
            "_formattedValue":"7,056.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-01-01",
            "_formattedValue":"1/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":11224,
            "_formattedValue":"11,224.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-02-01",
            "_formattedValue":"2/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":5857,
            "_formattedValue":"5,857.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-03-01",
            "_formattedValue":"3/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":8583,
            "_formattedValue":"8,583.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-04-01",
            "_formattedValue":"4/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":10156,
            "_formattedValue":"10,156.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-05-01",
            "_formattedValue":"5/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":8254,
            "_formattedValue":"8,254.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-06-01",
            "_formattedValue":"6/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":2871,
            "_formattedValue":"2,871.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-07-01",
            "_formattedValue":"7/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":6879,
            "_formattedValue":"6,879.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-08-01",
            "_formattedValue":"8/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":9720,
            "_formattedValue":"9,720.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-09-01",
            "_formattedValue":"9/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":3030,
            "_formattedValue":"3,030.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-10-01",
            "_formattedValue":"10/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":2147,
            "_formattedValue":"2,147.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-11-01",
            "_formattedValue":"11/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":6547,
            "_formattedValue":"6,547.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-12-01",
            "_formattedValue":"12/1/2019"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":5008,
            "_formattedValue":"5,008.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-01-01",
            "_formattedValue":"1/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":3872,
            "_formattedValue":"3,872.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-02-01",
            "_formattedValue":"2/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":3827,
            "_formattedValue":"3,827.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-03-01",
            "_formattedValue":"3/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":6102,
            "_formattedValue":"6,102.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-04-01",
            "_formattedValue":"4/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":4728,
            "_formattedValue":"4,728.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-05-01",
            "_formattedValue":"5/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":7347,
            "_formattedValue":"7,347.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-06-01",
            "_formattedValue":"6/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":9522,
            "_formattedValue":"9,522.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-07-01",
            "_formattedValue":"7/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":7029,
            "_formattedValue":"7,029.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-08-01",
            "_formattedValue":"8/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":10156,
            "_formattedValue":"10,156.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-09-01",
            "_formattedValue":"9/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":8254,
            "_formattedValue":"8,254.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-10-01",
            "_formattedValue":"10/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":2871,
            "_formattedValue":"2,871.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-11-01",
            "_formattedValue":"11/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":6879,
            "_formattedValue":"6,879.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-12-01",
            "_formattedValue":"12/1/2020"
         },
         {
            "_value":"TN",
            "_formattedValue":"TN"
         },
         {
            "_value":170,
            "_formattedValue":"170.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-01-01",
            "_formattedValue":"1/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":10920,
            "_formattedValue":"10,920.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-02-01",
            "_formattedValue":"2/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":11053,
            "_formattedValue":"11,053.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-03-01",
            "_formattedValue":"3/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":7128,
            "_formattedValue":"7,128.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-04-01",
            "_formattedValue":"4/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":6147,
            "_formattedValue":"6,147.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-05-01",
            "_formattedValue":"5/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":5341,
            "_formattedValue":"5,341.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-06-01",
            "_formattedValue":"6/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":4050,
            "_formattedValue":"4,050.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-07-01",
            "_formattedValue":"7/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":4126,
            "_formattedValue":"4,126.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-08-01",
            "_formattedValue":"8/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":12135,
            "_formattedValue":"12,135.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-09-01",
            "_formattedValue":"9/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":8794,
            "_formattedValue":"8,794.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-10-01",
            "_formattedValue":"10/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":8506,
            "_formattedValue":"8,506.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-11-01",
            "_formattedValue":"11/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":10377,
            "_formattedValue":"10,377.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2019-12-01",
            "_formattedValue":"12/1/2019"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":7577,
            "_formattedValue":"7,577.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-01-01",
            "_formattedValue":"1/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26298.6,
            "_formattedValue":"26,298.60"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-02-01",
            "_formattedValue":"2/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26317.2,
            "_formattedValue":"26,317.20"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-03-01",
            "_formattedValue":"3/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26334.6,
            "_formattedValue":"26,334.60"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-04-01",
            "_formattedValue":"4/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26353.2,
            "_formattedValue":"26,353.20"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-05-01",
            "_formattedValue":"5/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26371.2,
            "_formattedValue":"26,371.20"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-06-01",
            "_formattedValue":"6/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26389.8,
            "_formattedValue":"26,389.80"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-07-01",
            "_formattedValue":"7/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26407.8,
            "_formattedValue":"26,407.80"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-08-01",
            "_formattedValue":"8/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26426.399999999998,
            "_formattedValue":"26,426.40"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-09-01",
            "_formattedValue":"9/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":26445,
            "_formattedValue":"26,445.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-10-01",
            "_formattedValue":"10/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":125,
            "_formattedValue":"125.00"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-11-01",
            "_formattedValue":"11/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":-0.987,
            "_formattedValue":"-0.99"
         }
      ],
      [
         {
            "_value":"India",
            "_formattedValue":"India"
         },
         {
            "_value":"2020-12-01",
            "_formattedValue":"12/1/2020"
         },
         {
            "_value":"UP",
            "_formattedValue":"UP"
         },
         {
            "_value":12345,
            "_formattedValue":"12,345.00"
         }
      ]
   ],
   "_columns":[
      {
         "_fieldName":"Country",
         "_dataType":"string",
         "_isReferenced":true,
         "_index":0
      },
      {
         "_fieldName":"Periods",
         "_dataType":"date",
         "_isReferenced":true,
         "_index":1
      },
      {
         "_fieldName":"States",
         "_dataType":"string",
         "_isReferenced":true,
         "_index":2
      },
      {
         "_fieldName":"Measure 1",
         "_dataType":"float",
         "_isReferenced":true,
         "_index":3
      }
   ],
   "_totalRowCount":60,
   "_isTotalRowCountLimited":false,
   "_isSummaryData":false,
   "_name":"Underlying Data Table"
}